[package]
name = "arday11ChessLibrary"
version = "0.1.7"
edition = "2021"
description = "test"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
